services:
  mongo:
    image: mongo:7-jammy
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      # TODO use a named volume
      - mongo:/data/db
      # - ./data/db:/data/db
    env_file: [./mongodb/.env]
    command: [--auth]
  # api:
  #   image: mcr.microsoft.com/dotnet/samples:aspnetapp
  #   container_name: api
  #   ports:
  #     # - 80
  #     # - 443
  #     - 9000:80
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:9000
  #     #   - ASPNETCORE_URLS=https://+:443;http://+:80
  #     #   - ASPNETCORE_Kestrel__Certificates__Default__Password=password
  #     #   - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
  #   working_dir: /app
  #   volumes:
  #     # - ~/.aspnet/https:/https:ro
  #     # FIXME should be ./backend/Api. How to deal with multiple projects solution and a specific volume?
  #     - ./backend/Api:/app
  #   command: bash -c "dotnet run"
  #   depends_on:
  #     - mongo

volumes:
  mongo:
