services:
  mongo:
    image: mongo:7-jammy
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      # TODO use a named volume
      - mongo:/data/db
      # - ./data/db:/data/db
    env_file: [./mongodb/.env]
    command: [--auth]
  api:
    image: react-dotnet-api:1.0.0
    container_name: api
    ports:
      - 9000:80
    command: dotnet run
    depends_on:
      - mongo

volumes:
  mongo:
