services:
  mongo:
    image: mongo:7-jammy
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    env_file: [./mongodb/.env]
    command: [--auth]

volumes:
  mongo:
